spin_manifest_version = 2

[application]
name = "spintest"
version = "0.1.0"
description = ""

[[trigger.http]]
route = "/..."
component = "spintest"

[component.spintest]
source = "target/wasm32-wasi/release/spintest.wasm"
allowed_outbound_hosts = []
[component.spintest.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
