apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hello-world
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world-app
                port:
                  number: 80
