## Chart: argo/argo-cd
## Ref: https://github.com/argoproj/argo-helm/tree/argo-cd-4.9.4/charts/argo-cd
##

# Main Argo CD server replica count
server:
  replicas: 1
  env:
    - name: ARGOCD_API_SERVER_REPLICAS
      value: '1'

# Argo CD repository server replica count
repoServer:
  replicas: 1